version: '3.8'

services:
  app:
    image: aichat-app
    container_name: aichat-app
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - aichat-network
    # 设置资源限制（根据您服务器的实际情况调整）
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  aichat-network:
    driver: bridge 